### ISSUE TITLE
Dark mode button color

### ISSUE THREAD

**Issue by eshook** [ganast/tidybird#55]
Love the extension! A small feature request is to support darker buttons when in dark mode. The light gray buttons in dark mode stick out quite a bit.

If this does not make the supported feature list, then I totally understand and feel free to delete this request.

**Comment by tatankat** [comment]
Thanks!
Using the dark theme, you should get dark buttons since version 2.1 of the extension. This is what it should look like using the dark theme on Thunderbird 78 using version 3.2.1
![Screenshot_20220121_193606](https://user-images.githubusercontent.com/5812598/150582484-339c8f4b-8288-48f7-96ac-a4283ad4e50f.png)

What Thunderbird version are you using? Can you check the version of the extension (which you can see in the details of the extension when you click on it in the extensions list)? Maybe just try and (manually) install the latest version?

**Comment by eshook** [comment]
Indeed! I needed to update Thunderbird. Thank you again for the great extension! You can close this issue.
